### ISSUE TITLE
Handle panic and crash when user is returned as nill from Azure

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-msteams-meetings#24]
With 1 particular user, I am seeing the authentication  process  return a 500 and the plugin will crash. 
Other user are not affected. 

In any case, we should handle this to prevent the crash should anyone else come accross a case like this where something seems to be invalid with the users. 

See logs
```
{"level":"debug","ts":1603489636.774614,"caller":"web/handlers.go:100","msg":"Received HTTP request","method":"POST","url":"/api/v4/logs","request_id":"ho6mugii7bb5jbct4367eni1ge","status_code":"200"}
{"level":"debug","ts":1603489643.640474,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_update_active_status"}
{"level":"debug","ts":1603489647.0510972,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.mattermost.msteamsmeetings"}
{"level":"debug","ts":1603489647.05122,"caller":"plugin/hclog_adapter.go:53","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e792b6]","plugin_id":"com.mattermost.msteamsmeetings"}
{"level":"debug","ts":1603489647.051265,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"com.mattermost.msteamsmeetings"}
{"level":"debug","ts":1603489647.0513,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 6370 [running]:","plugin_id":"com.mattermost.msteamsmeetings"}
{"level":"debug","ts":1603489647.0513449,"caller":"plugin/hclog_adapter.go:53","msg":"main.(*Plugin).completeUserOAuth(0xc000387900, 0x2620680, 0xc0005f9650, 0xc000294300)","plugin_id":"com.mattermost.msteamsmeetings"}
{"level":"debug","ts":1603489647.051382,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-msteams-meetings/server/http.go:137 +0x7d6","plugin_id":"com.mattermost.msteamsmeetings"}
{"level":"debug","ts":1603489647.0514162,"caller":"plugin/hclog_adapter.go:53","msg":"main.(*Plugin).ServeHTTP(0xc000387900, 0xc00007ae40, 0x2620680, 0xc0005f9650, 0xc000294300)","plugin_id":"com.mattermost.msteamsmeetings"}
```

**Comment by DHaussermann** [comment]
@larkox there was not much point putting steps as they would need to be with my own user. Let me know if you need more details on this.
